### ISSUE TITLE
几个问题

### ISSUE THREAD

**Issue by shoyuf** [iq9891/vue-spa-template#1]
1. 动态加载路由的css文件没有合并，正常情况加载路由会加载两个文件。
2. https://github.com/iq9891/vue-spa-template/blob/75f33ac74f0b731227ec73e04c1e178097698e9e/template/build/webpack.development.conf.js#L21-L23  这个写法太奇葩，没有使用style lint根本跑不起来

**Comment by iq9891** [comment]
对不起哈，前几天就看看到了 issue ， 今天才处理，一直忙着开发别的耽误了。

刚才本地试了下，没遇到上述两个问题。
1.  目前只有生产环境打包的时候 css 文件才是按需加载的，其他情况都合并在一起的
2. stylelint没发现问题，但是jslint发现问题了。原因是没考虑到索引变化问题，已经修复了。[#a35334](https://github.com/iq9891/vue-spa-template/commit/a353345b905ed688e603228f972e42b769d42231)  

感谢反馈，多多支持🙂
